package sap_api_input_reader

type EC_MC struct {
	ConnectionKey string `json:"connection_key"`
	Result        bool   `json:"result"`
	RedisKey      string `json:"redis_key"`
	Filepath      string `json:"filepath"`
	Document      struct {
		DocumentNo      string `json:"document_no"`
		BusinessPartner string `json:"deliver_to"`
		Quantity        string `json:"quantity"`
		PickedQuantity  string `json:"picked_quantity"`
		Price           string `json:"price"`
		Batch           string `json:"batch"`
	} `json:"document"`
	ProductionOrder struct {
		DocumentNo           string `json:"document_no"`
		Status               string `json:"status"`
		DeliverTo            string `json:"deliver_to"`
		Quantity             string `json:"quantity"`
		CompletedQuantity    string `json:"completed_quantity"`
		PlannedStartDate     string `json:"planned_start_date"`
		PlannedValidatedDate string `json:"planned_validated_date"`
		ActualStartDate      string `json:"actual_start_date"`
		ActualValidatedDate  string `json:"actual_validated_date"`
		Batch                string `json:"batch"`
		Work                 struct {
			WorkNo                   string `json:"work_no"`
			Quantity                 string `json:"quantity"`
			CompletedQuantity        string `json:"completed_quantity"`
			ErroredQuantity          string `json:"errored_quantity"`
			Component                string `json:"component"`
			PlannedComponentQuantity string `json:"planned_component_quantity"`
			PlannedStartDate         string `json:"planned_start_date"`
			PlannedStartTime         string `json:"planned_start_time"`
			PlannedValidatedDate     string `json:"planned_validated_date"`
			PlannedValidatedTime     string `json:"planned_validated_time"`
			ActualStartDate          string `json:"actual_start_date"`
			ActualStartTime          string `json:"actual_start_time"`
			ActualValidatedDate      string `json:"actual_validated_date"`
			ActualValidatedTime      string `json:"actual_validated_time"`
		} `json:"work"`
	} `json:"production_order"`
	APISchema     string `json:"api_schema"`
	MaterialCode  string `json:"material_code"`
	Plant         string `json:"plant/supplier"`
	Stock         string `json:"stock"`
	DocumentType  string `json:"document_type"`
	DocumentNo    string `json:"document_no"`
	PlannedDate   string `json:"planned_date"`
	ValidatedDate string `json:"validated_date"`
	Deleted       bool   `json:"deleted"`
}

type SDC struct {
	ConnectionKey          string `json:"connection_key"`
	Result                 bool   `json:"result"`
	RedisKey               string `json:"redis_key"`
	Filepath               string `json:"filepath"`
	BusinessUserCollection struct {
		ObjectID                           string `json:"ObjectID"`
		ETag                               string `json:"ETag"`
		EmployeeID                         string `json:"EmployeeID"`
		EmployeeUUID                       string `json:"EmployeeUUID"`
		UserID                             string `json:"UserID"`
		TechnicalUserID                    string `json:"TechnicalUserID"`
		IdentityUUID                       string `json:"IdentityUUID"`
		BusinessPartnerID                  string `json:"BusinessPartnerID"`
		BusinessPartnerFormattedName       string `json:"BusinessPartnerFormattedName"`
		DepartmentName                     string `json:"DepartmentName"`
		CompanyName                        string `json:"CompanyName"`
		ManagerName                        string `json:"ManagerName"`
		EmailURI                           string `json:"EmailURI"`
		DecimalFormatCode                  string `json:"DecimalFormatCode"`
		DecimalFormatCodeText              string `json:"DecimalFormatCodeText"`
		DateFormatCode                     string `json:"DateFormatCode"`
		DateFormatCodeText                 string `json:"DateFormatCodeText"`
		TimeFormatCode                     string `json:"TimeFormatCode"`
		TimeFormatCodeText                 string `json:"TimeFormatCodeText"`
		TimeZoneCode                       string `json:"TimeZoneCode"`
		TimeZoneCodeText                   string `json:"TimeZoneCodeText"`
		LogonLanguageCode                  string `json:"LogonLanguageCode"`
		LogonLanguageCodeText              string `json:"LogonLanguageCodeText"`
		UserValidityStartDate              string `json:"UserValidityStartDate"`
		UserValidityEndDate                string `json:"UserValidityEndDate"`
		UserLockedIndicator                bool   `json:"UserLockedIndicator"`
		UserCountedIndicator               bool   `json:"UserCountedIndicator"`
		PasswordPolicyCode                 string `json:"PasswordPolicyCode"`
		PasswordPolicyCodeText             string `json:"PasswordPolicyCodeText"`
		PasswordInactiveIndicator          bool   `json:"PasswordInactiveIndicator"`
		PasswordLockedIndicator            bool   `json:"PasswordLockedIndicator"`
		UserAccountTypeCode                string `json:"UserAccountTypeCode"`
		UserAccountTypeCodeText            string `json:"UserAccountTypeCodeText"`
		CreatedOn                          string `json:"CreatedOn"`
		UserCreatedBy                      string `json:"UserCreatedBy"`
		EntityLastChangedOn                string `json:"EntityLastChangedOn"`
		UserChangedBy                      string `json:"UserChangedBy"`
		UserChangedOn                      string `json:"UserChangedOn"`
		BusinessUserBusinessRoleAssignment struct {
			ObjectID            string `json:"ObjectID"`
			ParentObjectID      string `json:"ParentObjectID"`
			EmployeeID          string `json:"EmployeeID"`
			UserID              string `json:"UserID"`
			BusinessRoleID      string `json:"BusinessRoleID"`
			EntityLastChangedOn string `json:"EntityLastChangedOn"`
			EmployeeBasicData   struct {
				ObjectID                         string `json:"ObjectID"`
				ETag                             string `json:"ETag"`
				EmployeeID                       string `json:"EmployeeID"`
				EmployeeUUID                     string `json:"EmployeeUUID"`
				UserID                           string `json:"UserID"`
				IdentityUUID                     string `json:"IdentityUUID"`
				BusinessPartnerID                string `json:"BusinessPartnerID"`
				CurrentInternalEmployeeIndicator bool   `json:"CurrentInternalEmployeeIndicator"`
				CurrentExternalEmployeeIndicator bool   `json:"CurrentExternalEmployeeIndicator"`
				FormattedName                    string `json:"FormattedName"`
				TitleCode                        string `json:"TitleCode"`
				AcademicTitleCode                string `json:"AcademicTitleCode"`
				FirstName                        string `json:"FirstName"`
				MiddleName                       string `json:"MiddleName"`
				LastName                         string `json:"LastName"`
				SecondLastName                   string `json:"SecondLastName"`
				NickName                         string `json:"NickName"`
				GenderCode                       string `json:"GenderCode"`
				LanguageCode                     string `json:"LanguageCode"`
				FormattedAddress                 string `json:"FormattedAddress"`
				CountryCode                      string `json:"CountryCode"`
				RegionCode                       string `json:"RegionCode"`
				AddressLine1                     string `json:"AddressLine1"`
				AddressLine2                     string `json:"AddressLine2"`
				HouseNumber                      string `json:"HouseNumber"`
				Street                           string `json:"Street"`
				AddressLine4                     string `json:"AddressLine4"`
				AddressLine5                     string `json:"AddressLine5"`
				City                             string `json:"City"`
				PostalCode                       string `json:"PostalCode"`
				Phone                            string `json:"Phone"`
				Mobile                           string `json:"Mobile"`
				Fax                              string `json:"Fax"`
				Email                            string `json:"Email"`
				UserValidityStartDate            string `json:"UserValidityStartDate"`
				UserValidityEndDate              string `json:"UserValidityEndDate"`
				UserPasswordPolicyCode           string `json:"UserPasswordPolicyCode"`
				UserLockedIndicator              bool   `json:"UserLockedIndicator"`
				TimeZoneCode                     string `json:"TimeZoneCode"`
				ManagerUUID                      string `json:"ManagerUUID"`
				ManagerFormattedName             string `json:"ManagerFormattedName"`
				JobName                          string `json:"JobName"`
				CreatedOn                        string `json:"CreatedOn"`
				CreatedBy                        string `json:"CreatedBy"`
				ChangedOn                        string `json:"ChangedOn"`
				ChangedBy                        string `json:"ChangedBy"`
				EntityLastChangedOn              string `json:"EntityLastChangedOn"`
			} `json:"EmployeeBasicData"`
		} `json:"BusinessUserBusinessRoleAssignment"`
	} `json:"BusinessUserCollection"`
	APISchema        string   `json:"api_schema"`
	Accepter         []string `json:"accepter"`
	BusinessUserCode string   `json:"business_user_code"`
	Deleted          bool     `json:"deleted"`
}
